version: "3.8"
services:
  redis:
    image: redis:6.2.6-alpine3.15
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  producer:
    build:
      context: redis-stream-tracing-producer
    environment:
      - SPRING_REDIS_HOST=redis
    ports:
      - 8080:8080

  consumer:
    build:
      context: redis-stream-tracing-consumer
    environment:
      - SPRING_REDIS_HOST=redis

volumes:
  redis_data: